spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-db
    username: postgres
    password: 'postgre'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-plateform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  main:
    allow-circular-references: true
    #web-application-type: none
  devtools:
    restart:
      enabled: false
jwt:
  secret: covidcentre
  token:
    prefix: Bearer

management:
  endpoints:
    jmx:
      exposure:
        include: info,health,beans,metrics,endpoints,mappings
    web:
      exposure:
        include: health,info,prometheus,metrics

#server:
#  port: 12037
logging:
  level:
    io:
      micrometer: DEBUG

#path:
#  centres: D:\Polytech\5A\Fullstack\Projet\covid-api\src\main\resources\centres-vaccination.csv