spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-db
    username: postgres
    password: 'postgre'
  jpa:
    database-plateform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB